name: 'Destroy Terraform Objects'
on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Resource to destroy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - resource_group
          - storage_account
          - service_plan
          - function_app

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Authenticate to Azure
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./ops/terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./ops/terraform

      - name: Plan Terraform Destroy
        run: |
          echo "Running terraform destroy plan for resource: ${{ github.event.inputs.resource }}"
          case ${{ github.event.inputs.resource }} in
            all)
              terraform plan -destroy -out=tfplan
              ;;
            resource_group)
              terraform plan -destroy -target=azurerm_resource_group.main -out=tfplan
              ;;
            storage_account)
              terraform plan -destroy -target=azurerm_storage_account.main -out=tfplan
              ;;
            service_plan)
              terraform plan -destroy -target=azurerm_service_plan.main -out=tfplan
              ;;
            function_app)
              terraform plan -destroy -target=azurerm_function_app.main -out=tfplan
              ;;
          esac
        working-directory: ./ops/terraform

      - name: Apply Terraform Destroy
        run: terraform apply -auto-approve tfplan
        working-directory: ./ops/terraform